# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26a9d4e2293d0570fa422598ce2a68be8b04b04c00d58f474d76aa39ed725321fcc42baf4cf4fc18eb85cf47cab740e32d82ebe8155427b2c7c6700cff0f8ff8

test:
  secret_key_base: f4da45b111916c638896c76f3a9d88703ea9a378445f15d0435d2efd83779c2d84c268817d455657bf350667467f7e1cf7c0301bfd3b938fa0210c50197fe0fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
